name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection
        run:  |
              echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
              chmod 600 ec2_key.pem
              ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }} "echo SSH connection successful"
