name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        run: echo "CD will deploy here"
